

window.DATA = {

  heroVideo: '',

  heroSlides: [
    'assets/photos/home/home-1.webp',
    'assets/photos/home/home-2.webp',
    'assets/photos/home/home-3.webp',
    'assets/photos/home/home-4.webp',
  ],

  facilities: [
    {
      id: 'rooms',
      name: 'Номера',
      nameKey: 'facilities.rooms_name',
      desc: 'Шесть категорий — от стандарта до апартаментов',
      descKey: 'facilities.rooms_desc',
      img: 'assets/photos/rooms/apartments-1.webp',
    },
    {
      id: 'restaurant',
      name: 'Гастрономия',
      nameKey: 'facilities.restaurant_name',
      desc: 'Пространство сдержанной элегантности',
      descKey: 'facilities.restaurant_desc',
      img: 'assets/photos/restaurant/veranda-11.webp',
    },
    {
      id: 'banquet',
      name: 'Банкетный зал',
      nameKey: 'facilities.banquet_name',
      desc: 'Для торжеств и деловых событий',
      descKey: 'facilities.banquet_desc',
      img: 'assets/photos/banquet/main-7.webp',
    },
    {
      id: 'contacts',
      name: 'Контакты',
      nameKey: 'facilities.contacts_name',
      desc: 'Связь и расположение',
      descKey: 'facilities.contacts_desc',
      img: 'assets/photos/restaurant/billiard-4.webp',
    },
  ],

  rooms: [
    {
      name: 'Стандарт',
      nameKey: 'rooms.standard_name',
      area: '27',
      price: '28 000 ₸',
      description: 'Одноместный номер с полуторной кроватью (140×200). Мини-бар, кондиционер, кабельное ТВ, беспроводной интернет, телефон с междугородним подключением, сейф. Завтрак включён в стоимость.',
      descKey: 'rooms.standard_desc',
      image: 'assets/photos/rooms/standard-2.webp',
      images: [
        'assets/photos/rooms/standard-2.webp',
        'assets/photos/rooms/standard-1.webp',
        'assets/photos/rooms/standard-3.webp',
      ],
    },
    {
      name: 'Полулюкс',
      nameKey: 'rooms.polulux_name',
      area: '48',
      price: '34 000 ₸',
      description: 'Просторный номер с двуспальной кроватью 180×200. Возможно двухместное размещение с доплатой. Полный набор удобств: мини-бар, кондиционер, кабельное ТВ, интернет, сейф. Завтрак включён.',
      descKey: 'rooms.polulux_desc',
      image: 'assets/photos/rooms/polulux-1.webp',
      images: [
        'assets/photos/rooms/polulux-1.webp',
        'assets/photos/rooms/polulux-2.webp',
        'assets/photos/rooms/polulux-3.webp',
      ],
    },
    {
      name: 'Двухместный полулюкс',
      nameKey: 'rooms.polulux_twin_name',
      area: '27',
      price: '45 000 ₸',
      description: 'Две раздельные кровати 120×200 — идеально для двух гостей. Мини-бар, кондиционер, кабельное ТВ, интернет, сейф. Завтрак включён.',
      descKey: 'rooms.polulux_twin_desc',
      image: 'assets/photos/rooms/polulux-twin-2.webp',
      images: [
        'assets/photos/rooms/polulux-twin-2.webp',
        'assets/photos/rooms/polulux-twin-1.webp',
        'assets/photos/rooms/polulux-twin-3.webp',
      ],
    },
    {
      name: 'Семейный',
      nameKey: 'rooms.family_name',
      area: '65',
      price: '55 000 ₸',
      description: 'Три комнаты: две спальни и гостиная. Трёхместное или четырёхместное размещение. Полный набор удобств. Завтрак включён в стоимость номера.',
      descKey: 'rooms.family_desc',
      image: 'assets/photos/rooms/family-1.webp',
      images: [
        'assets/photos/rooms/family-1.webp',
        'assets/photos/rooms/family-2.webp',
        'assets/photos/rooms/family-3.webp',
        'assets/photos/rooms/family-4.webp',
      ],
    },
    {
      name: 'Люкс',
      nameKey: 'rooms.lux_name',
      area: '65',
      price: '44 000 ₸',
      description: 'Две комнаты: спальня и гостиная. Двуспальная кровать 180×200. Мини-бар, кондиционер, кабельное ТВ, интернет, сейф. Завтрак включён.',
      descKey: 'rooms.lux_desc',
      image: 'assets/photos/rooms/lux-1.webp',
      images: [
        'assets/photos/rooms/lux-1.webp',
        'assets/photos/rooms/lux-2.webp',
        'assets/photos/rooms/lux-3.webp',
      ],
    },
    {
      name: 'Апартамент',
      nameKey: 'rooms.apartments_name',
      area: '130',
      price: '100 000 ₸',
      description: 'Высшая категория. Три комнаты: спальня, гостиная с обеденной и мягкой зонами, отдельный кабинет. Душевая кабина и джакузи, двуспальная кровать 180×200. Полный набор удобств, комплимент от гостиницы — свежие фрукты по приезду.',
      descKey: 'rooms.apartments_desc',
      image: 'assets/photos/rooms/apartments-4.webp',
      images: [
        'assets/photos/rooms/apartments-4.webp',
        'assets/photos/rooms/apartments-1.webp',
        'assets/photos/rooms/apartments-2.webp',
        'assets/photos/rooms/apartments-3.webp',
        'assets/photos/rooms/apartments-5.webp',
        'assets/photos/rooms/apartments-6.webp',
        'assets/photos/rooms/apartments-7.webp',
      ],
    },
  ],

  venues: [
    {
      name: 'Летняя веранда',
      nameKey: 'venues.veranda_name',
      subtitle: 'Medeu',
      subtitleKey: 'venues.veranda_subtitle',
      tagline: 'Оазис в самом центре города',
      taglineKey: 'venues.veranda_tagline',
      description: 'Первый этаж расположен в тени деревьев. Комфортные мягкие зоны готовы принять самых искушённых гостей. Отлично подходит для семейного отдыха — есть прекрасная детская зона с батутом, где маленьким гостям не будет скучно.',
      descKey: 'venues.veranda_desc',
      image: 'assets/photos/restaurant/veranda-7.webp',
      images: [
        'assets/photos/restaurant/veranda-7.webp',
        'assets/photos/restaurant/veranda-1.webp',
        'assets/photos/restaurant/veranda-2.webp',
        'assets/photos/restaurant/veranda-3.webp',
        'assets/photos/restaurant/veranda-4.webp',
        'assets/photos/restaurant/veranda-5.webp',
        'assets/photos/restaurant/veranda-6.webp',
        'assets/photos/restaurant/veranda-8.webp',
        'assets/photos/restaurant/veranda-9.webp',
        'assets/photos/restaurant/veranda-10.webp',
        'assets/photos/restaurant/veranda-11.webp',
        'assets/photos/restaurant/veranda-12.webp',
        'assets/photos/restaurant/veranda-13.webp',
      ],
    },
    {
      name: 'Lounge-ресторан',
      nameKey: 'venues.medeu_name',
      subtitle: 'Medeu',
      subtitleKey: 'venues.medeu_subtitle',
      tagline: 'Пространство с атмосферой сдержанной элегантности',
      taglineKey: 'venues.medeu_tagline',
      description: 'Эффектное двухуровневое пространство с комфортной посадкой и атмосферой lounge-ресторана. Создано для гастрономических встреч и деловых ужинов. Работаем ежедневно с\u00A007:30 до\u00A001:00. Шведский стол — 07:30–10:30 (5\u00A0000\u00A0₸/чел). Бизнес-ланчи по будням 12:00–15:00.',
      descKey: 'venues.medeu_desc',
      image: 'assets/photos/restaurant/medeu-6.webp',
      images: [
        'assets/photos/restaurant/medeu-6.webp',
        'assets/photos/restaurant/medeu-0.webp',
        'assets/photos/restaurant/medeu-1.webp',
        'assets/photos/restaurant/medeu-2.webp',
        'assets/photos/restaurant/medeu-3.webp',
        'assets/photos/restaurant/medeu-4.webp',
      ],
    },
    {
      name: 'Lounge-пространство с караоке',
      nameKey: 'venues.karaoke_name',
      subtitle: 'kazakhka',
      subtitleKey: 'venues.karaoke_subtitle',
      tagline: 'В атмосфере паназиатской эстетики',
      taglineKey: 'venues.karaoke_tagline',
      description: 'Уютное приватное пространство, сочетающее современный интерьер, атмосферу паназиатского стиля и комфортный формат отдыха для небольших компаний и закрытых мероприятий. Аренда — 6\u00A0000\u00A0₸/час, после 24:00 — 10\u00A0000\u00A0₸/час.',
      descKey: 'venues.karaoke_desc',
      image: 'assets/photos/restaurant/karaoke-1.webp',
      images: [
        'assets/photos/restaurant/karaoke-1.webp',
        'assets/photos/restaurant/karaoke-2.webp',
        'assets/photos/restaurant/karaoke-3.webp',
        'assets/photos/restaurant/karaoke-4.webp',
      ],
    },
    {
      name: 'Камерный зал',
      nameKey: 'venues.billiard_name',
      subtitle: 'Бильярд',
      subtitleKey: 'venues.billiard_subtitle',
      tagline: 'Пространство для приватных мероприятий',
      taglineKey: 'venues.billiard_tagline',
      description: 'Элегантное пространство с атмосферой уединённого комфорта, идеально подходящее для частных встреч, семейных торжеств и закрытых мероприятий. Современный европейский интерьер с акцентом на комфорт и приватность.',
      descKey: 'venues.billiard_desc',
      image: 'assets/photos/restaurant/billiard-3.webp',
      images: [
        'assets/photos/restaurant/billiard-3.webp',
        'assets/photos/restaurant/billiard-1.webp',
        'assets/photos/restaurant/billiard-2.webp',
        'assets/photos/restaurant/billiard-4.webp',
        'assets/photos/restaurant/billiard-5.webp',
        'assets/photos/restaurant/billiard-6.webp',
      ],
    },
  ],

  banquetSlides: [
    'assets/photos/banquet/main-7.webp',
    'assets/photos/banquet/main-10.webp',
    'assets/photos/banquet/main-9.webp',
  ],
  conferenceImage: 'assets/photos/banquet/conference-2.webp',
  conferenceImages: [
    'assets/photos/banquet/conference-2.webp',
    'assets/photos/banquet/conference-1.webp',
  ],

  services: [
    {
      name: 'Thai SPA',
      nameKey: 'services.spa_name',
      subtitle: 'Тайский массаж и СПА',
      subtitleKey: 'services.spa_subtitle',
      description: 'Тайский массаж, СПА-программы, хамам, бассейн. Работают мастера из Таиланда. Гостям гостиницы — скидка 10%.',
      descKey: 'services.spa_desc',
      phone: '+7 (707) 587-90-90',
      waNumber: '77075879090',
      icon: 'spa',
    },
    {
      name: 'Химчистка',
      nameKey: 'services.laundry_name',
      subtitle: 'Услуги прачечной',
      subtitleKey: 'services.laundry_subtitle',
      description: 'Стирка, химчистка, глажка одежды. Работаем ежедневно с 8:00 до 20:00. Срочные заказы — по согласованию.',
      descKey: 'services.laundry_desc',
      phone: '+7 (707) 317-88-95',
      waNumber: '77073178895',
      hours: '8:00 – 20:00 ежедневно',
      hoursKey: 'services.laundry_hours',
      icon: 'laundry',
    },
    {
      name: 'Трансфер',
      nameKey: 'services.transfer_name',
      subtitle: 'Аэропорт, вокзал, выезды',
      subtitleKey: 'services.transfer_subtitle',
      description: 'Трансфер «гостиница ↔ аэропорт», встреча с табличкой, почасовая аренда автомобиля с водителем, выезды по области.',
      descKey: 'services.transfer_desc',
      phone: '+7 (7142) 545-845',
      waNumber: '77714944599',
      icon: 'transfer',
    },
    {
      name: 'Прокат велосипедов',
      nameKey: 'services.bike_name',
      subtitle: 'Для прогулок по городу',
      subtitleKey: 'services.bike_subtitle',
      description: 'Прокат велосипедов для прогулок по Костанаю. Удобный способ познакомиться с городом в тёплое время года.',
      descKey: 'services.bike_desc',
      phone: '+7 (7142) 545-845',
      waNumber: '77714944599',
      icon: 'bike',
    },
    {
      name: 'Оформление праздничного стола',
      nameKey: 'services.decor_name',
      subtitle: 'Декор для торжеств',
      subtitleKey: 'services.decor_subtitle',
      description: 'Оформление праздничного стола цветами и декором для дней рождения, юбилеев, корпоративов в нашем ресторане или банкетном зале.',
      descKey: 'services.decor_desc',
      phone: '+7 (775) 521-57-06',
      waNumber: '77755215706',
      icon: 'decor',
    },
  ],

  restoplaceId: '57d0bcbf4b55ea8a0b4f',

  pageHero: {
    rooms:      'assets/photos/rooms/lux-1.webp',
    restaurant: 'assets/photos/restaurant/gastronomy-hero-1.webp',
    banquet:    'assets/photos/banquet/main-10.webp',
    services:   'assets/photos/restaurant/billiard-4.webp',
  },

  /* Слайды для hero-карусели на внутренних страницах.
     Если массив есть — page-hero превращается в карусель.
     Если нет — используется одна картинка из pageHero[id]. */
  pageHeroSlides: {
    restaurant: [
      'assets/photos/restaurant/gastronomy-hero-1.webp',
      'assets/photos/restaurant/gastronomy-hero-2.webp',
      'assets/photos/restaurant/gastronomy-hero-3.webp',
      'assets/photos/restaurant/gastronomy-hero-4.webp',
      'assets/photos/restaurant/gastronomy-hero-5.webp',
    ],
  },

  contacts: {
    address: 'Республика Казахстан, г. Костанай, ул. Баймагамбетова 166а',

    phone1: '+7 (7142) 545-845',
    phone2: '+7 (771) 494-45-99',
    email:  'info@medeuhotel.kz',

    hotelPhones: [
      { label: 'Ресепшн',       number: '+7 (7142) 545-845' },
      { label: 'Факс',          number: '+7 (7142) 545-945' },
      { label: 'Моб. ресепшн',  number: '+7 (771) 494-45-99' },
    ],
    restaurantPhones: [
      { label: 'Администратор',      number: '+7 (7142) 545-884' },
      { label: 'Моб. администратор', number: '+7 (707) 329-16-35' },
      { label: 'Банкетный зал',      number: '+7 (775) 521-57-06' },
    ],
    laundry: {
      hours: '8:00 – 20:00 ежедневно',
      phone: '+7 (707) 317-88-95',
    },

    waReception:  '77714944599',
    waRestaurant: '77073291635',
    waBanquet:    '77755215706',

    formspreeUrl: 'https://formspree.io/f/xjgzbqoo',
    bookingEmail: 'info@medeuhotel.kz',

    instagram: 'https://www.instagram.com/hotel_medeu_kostanay/',
    facebook:  '',

    gis2Url:   'https://go.2gis.com/M2V07',
    googleUrl: 'https://maps.app.goo.gl/ndN3XnVWUE4iur318',
  },
};
